# 端口
server:
  port: 9999

# 打开客户端的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
  endpoint:
    health:
      show-details: always # 访问/actuator/health时，显示详细信息，而不是仅仅显示"status": "UP"

spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: http://localhost:8888 #admin server的地址列表
        username: admin
        password: admin
        instance:
          service-url: http://localhost:9999 #当前系统地址
          name: admin-client-instance
          metadata:
            user.name: admin
            user.password: admin

logging:
  file:
    name: D:/logs/actuator-admin-client.log
