# 端口
server:
  port: 8888

spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      ui:
        title: "我的监控中心"
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>我的监控中心（Spring Boot Admin）</span>"

logging:
  file:
    name: D:/logs/actuator-admin-service.log
