# 打开客户端的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 7777

spring:
  application:
    name: admin-client2
  boot:
    admin:
      client:
        url: http://localhost:8888 #admin server的地址列表
        username: admin
        password: admin
        instance:
          service-url: http://localhost:7777 #当前系统地址
          name: admin-client2-instance
        metadata:
          # 这里配置admin-client的账号和密码
          user.name: admin
          user.password: admin

  # Mysql配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://127.0.0.1:3306/hola?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: D:/logs/actuator-admin-client2.log
