# 端口
server:
  port: 9999

# 打开客户端的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
  #        exclude: env,beans # 排除环境和类
  endpoint:
    health:
      show-details: always # 访问/actuator/health时，显示详细信息，而不是仅仅显示"status": "UP"
    loggers:
      enabled: true

# 如果服务端配置了验证，客户端就需要设置用户名和密码
spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        url: http://localhost:8888 #admin server的地址列表
        username: admin
        password: admin
        instance:
          service-url: http://localhost:${server.port} #当前系统地址
          name: admin-client-instance1-port-${server.port}
          metadata: # 元数据
            user.name: admin
            user.password: admin

logging:
  file:
    name: D:/logs/actuator-admin-client.log
